# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e08f1208b5a6ffc4bd1dc25a729d0e23da62f70d3fa7cea7ed813f737c7c36e3f9a724c996e87947dad09fb4661426760f87d6497686914bae48b5c250a86bc1

test:
  secret_key_base: 1c38486ed467aeb503bf8fb82c1665342b8500934067aac226d0a0bd523d3f8f6b379cbfc5b9cedb106400e933975626f2c4ba6bae87bf47b9b44f23ab0648e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
